server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: leads
        uri: lb://leads
        predicates:
        - Path=/leads/**
      - id: users
        uri: lb://users
        predicates:
        - Path=/users/**